stages:
  - test
  - bundle
  - build
  - e2e

test:
  image: leapcode/soledad:latest
  stage: test
  script:
    - tox --recreate -e py27-dev

bitmask_latest_bundle:
  image: leapcode/bitmask-dev:latest
  stage: bundle
  script: pkg/build_bundle_with_venv.sh
  artifacts:
    paths:
      - dist/bitmask-*
    name: "Bitmask_linux64_latest_${CI_BUILD_REF}"
    expire_in: 1 month

build_ui:
  image: leapcode/bitmask-dev:latest
  stage: build
  script:
    - cd ui && make dev-build

e2e_tests:
  image: leapcode/bitmask-dev:latest
  stage: e2e
  allow_failure: true
  script:
    - virtualenv venv
    - source venv/bin/activate
    - make dev-latest-backend
    - mkdir -p /root/.config/leap/
    - apt install swaks
    - make test_e2e
